spring:
  profiles:
    active:
    - dev
---
server:
  port: 6001

spring:
  profiles: test
  application:
    name: operconfigprovider6001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: oracle.jdbc.driver.OracleDriver              # mysql驱动包
    url: jdbc:oracle:thin:@localhost:1521:orcl              # 数据库名称
    username: system
    password: ADMIN
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

mybatis:
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:5001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: operconfigprovider6001
    prefer-ip-address: true     #访问路径可以显示IP地址
    
---
server:
  port: 6001

spring:
  profiles: dev
  application:
    name: operconfigprovider6001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: oracle.jdbc.driver.OracleDriver              # mysql驱动包
    url: jdbc:oracle:thin:@localhost:1521:orcl              # 数据库名称
    username: system
    password: ADMIN
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

mybatis:
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:5001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: operconfigprovider6001
    prefer-ip-address: true     #访问路径可以显示IP地址